version: '3.9'

services:
  web:
    build: .
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - db
    links:
      - db:db
  db:
    restart: always
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: 'carservice_test'
      POSTGRES_USER: 'admin'
      POSTGRES_PASSWORD: 'admin'


volumes:
  postgres_data:
